### ISSUE TITLE
No rule to make target 'algorithm/xevan.c', needed by 'algorithm/sgminer-xevan.o'.  Stop.

### ISSUE THREAD

**Issue by cdarken** [brian112358/avermore-miner#4]
I think you forgot to commit the header and the src file for xevan.

**Comment by brian112358** [comment]
I added the xevan src/header files in the Makefile.am [here](https://github.com/brian112358/avermore-miner/commit/6b01f8fc53517d2e46ddad9219eac9aad1473dfb#diff-c949f93d03f44a4217d7a138f9e2e54aR75). Make sure you run `autoreconf -i` before compiling, since autoconf needs to generate a new Makefile with the xevan files included.

**Comment by cdarken** [comment]
Yes, they are referred, but you didn't commit the actual files in algorithm directory, xevan.h and xevan.c

**Comment by brian112358** [comment]
Wow, I'm an idiot. Just pushed them to the repo in [this commit](https://github.com/brian112358/avermore-miner/commit/f1e52ea089e75254bcd0caad5171454c9efcda68). Thanks for the catch.

**Comment by cdarken** [comment]
Np. All is fine now.
